const mongoose = require("mongoose");
const { Schema } = mongoose;

const encuestaSchema = new Schema({
  "Metadatos de la encuesta - Fecha de inicio (+00:00 GMT)": Date,
  "Metadatos de la encuesta - Fecha de finalización (+00:00 GMT)": Date,
  "Metadatos de la encuesta - Dirección IP": String,
  "Metadatos de la encuesta - Finalizado": String,
  "Metadatos de la encuesta - Fecha registrada (+00:00 GMT)": Date,
  "Campos de contacto - Correo electrónico del destinatario": String,
  "1 - ¿Sos la persona que se comunicó con nuestro centro de atención?": String,
  "(Grupo) 2_NPS_GROUP - En base a tu último contacto realizado, ¿qué probabilidad hay de que recomi...":
    String,
  "2 - En base a tu último contacto realizado, ¿qué probabilidad hay de que recomi...":
    Number,
  "3 - ¿Cuál es el motivo de tu calificación?": String,
  "5_2 - La facilidad y claridad de nuestro menú de opciones": String,
  "5_3 - El tiempo que tuviste que esperar hasta ser atendido": String,
  "5_6 - La cordialidad del representante": String,
  "5_7 - La claridad de la información suministrada por el representante":
    String,
  "5_8 - El conocimiento del representante para resolver tu consulta": String,
  "6 - La consulta por la cual te comunicaste, ¿quedó resuelta al finalizar el con...":
    String,
  "Datos embebidos - EMPRESA": String,
  "Datos embebidos - CAMP": String,
  "Datos embebidos - TABULACION1": String,
  "Datos embebidos - TABULACION2": String,
  "Datos embebidos - TABULACION3": String,
  "Datos embebidos - TABULACION4": String,
  "Datos embebidos - AGRUPADOR1": String,
  "Datos embebidos - AGRUPADOR2": String,
  "Datos embebidos - AGRUPADOR3": String,
  "Datos embebidos - AGRUPADOR3_1": String,
  "Datos embebidos - SEGMENTO": String,
  "Datos embebidos - ID_SUSCRIPCION": Number,
  "Datos embebidos - PROVINCIA": String,
  "Datos embebidos - VQ": String,
  "Datos embebidos - INTERACTION_ID": Number,
  "Datos embebidos - FECHA (+00:00 GMT)": Number,
  "Datos embebidos - ANI": Number,
  "Datos embebidos - PCRC": String,
  "Datos embebidos - PCRC1": String,
  "Datos embebidos - PCRC2": String,
  "Datos embebidos - PCRC3": String,
  "Datos embebidos - ID_CLIENTE": Number,
  "Datos embebidos - PARTIDO": String,
  "Datos embebidos - FLAG_MASIVO": Number,
  "Datos embebidos - FLAG_SERVICE": Number,
  "Datos embebidos - FLAG_RESUELVE": Number,
  "Datos embebidos - DESC_PRODUCTO": String,
  "Datos embebidos - CLASIFICACION7": String,
  "Datos embebidos - Menú de Opciones": String,
  "Datos embebidos - Tiempo Espera Atención": String,
  "Datos embebidos - Cordialidad": String,
  "Datos embebidos - Claridad de la Información": String,
  "Datos embebidos - Conocimiento": String,
  "3 - ¿Cuál es el motivo de tu calificación? - Sentiment": String,
  "3 - ¿Cuál es el motivo de tu calificación? - Sentiment Score": Number,
  "3 - ¿Cuál es el motivo de tu calificación? - Sentiment Polarity": Number,
  "3 - ¿Cuál es el motivo de tu calificación? - Topic Sentiment Label": String,
  "3 - ¿Cuál es el motivo de tu calificación? - Topic Sentiment Score": String,
  "3 - ¿Cuál es el motivo de tu calificación? - Topics": String,
  "Datos embebidos - Concatenado - Tabulaciones": String,
  "Datos embebidos - AGENTE_RP": String,
  "Datos embebidos - Filtro_FTTH_VQ": String,
  "Datos embebidos - NEGOCIO": String,
  MVP_CUMPLIMIENTO: String,
  MVP_PORTAL: String,
  MVP_SOPORTE: String,
  MVP_FACTURA_PERSO: String,
  MVP_FACTURA_CABLE: String,
  MVP_SOPORTE_HHBB: String,
  MVP_AV_FAN: String,
  POND_TAB1: String,
  "Datos embebidos - Filtro_FTTH_Clientes": String,
  "Datos embebidos - SITIO": String,
  "Datos embebidos - CONVERGENTE": String,
  FILTRO_FTTH_OK: String,
  INTERACTION_RESOURCE_ID: Number,
  "Datos embebidos - TABULACION 1 | TABULACION 2": String,
  MVP_INTERNET_HFC: String,
  MVP_FACTURA_AVFAN: String,
  "Datos embebidos - VAG": String,
  SCORE_CLIENTE: Number,
  "Campos de contacto - Canal de la distribucion": String,
  "Campos de contacto - Canal de la distribucion 2": String,
  "TABULACION 1": String,
  "TABULACION 2": String,
  "TABULACION 3": String,
  "TABULACION 4": String,
  "_cachedDate (+00:00 GMT)": Number,
  _recordId: String,
  "_recordedDate (+00:00 GMT)": Number,
  _sourceId: String,
  _sourceMapId: String,
  _sourceType: String,
});

// Define el modelo basado en el esquema
const encuesta = mongoose.model("encuesta", encuestaSchema);

module.exports = encuesta;
